{'application': False,
 'author': 'etech',
 'auto_install': False,
 'category': 'Website',
 'contributors': 'etech',
 'currency': 'EUR',
 'data': ['security/ir.model.access.csv',
          'views/assets.xml',
          'views/website_modal.xml',
          'views/templates.xml'],
 'demo': [],
 'depends': ['website'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainer': 'etech',
 'name': 'Popups',
 'price': 30.0,
 'qweb': [],
 'summary': 'Show popups when visiting, exiting or reading page',
 'version': '14.0.1.0.0',
 'website': 'https://www.etechconsulting-mg.com/'}
